<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-EUH2O3V" failures="4" tests="9" name="com.app.runner.TestNGRunner" time="307.709" errors="0" timestamp="2024-01-20T10:11:41 IST" skipped="4">
  <testcase classname="com.app.runner.TestNGRunner" name="runScenario" time="33.426">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.app.stepdefs.Steps.it_shoulld_diplayed_the_message(Steps.java:101)
at ✽.It shoulld diplayed the message 'It is mandontary to fill the fields'(file:///C:/Users/DELL/eclipse-workspace/RLL_Project_ContactUs/RLL_project_ContactUsForm/src/test/resource/features/ContactUs.feature:14)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.app.runner.TestNGRunner" name="runScenario" time="35.209">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.app.runner.TestNGRunner" name="runScenario" time="35.527"/>
  <system-out/>
  <testcase classname="com.app.runner.TestNGRunner" name="runScenario" time="33.375">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.app.stepdefs.Steps.it_shoulld_diplayed_the_message(Steps.java:101)
at ✽.It shoulld diplayed the message 'Please enter the valid email'(file:///C:/Users/DELL/eclipse-workspace/RLL_Project_ContactUs/RLL_project_ContactUsForm/src/test/resource/features/ContactUs.feature:14)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.app.runner.TestNGRunner" name="runScenario" time="33.340">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.app.stepdefs.Steps.it_shoulld_diplayed_the_message(Steps.java:101)
at ✽.It shoulld diplayed the message 'Please enter the valid name'(file:///C:/Users/DELL/eclipse-workspace/RLL_Project_ContactUs/RLL_project_ContactUsForm/src/test/resource/features/ContactUs.feature:14)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.app.runner.TestNGRunner" name="runScenario" time="35.520">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.app.runner.TestNGRunner" name="runScenario" time="35.493">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.app.stepdefs.Steps.it_shoulld_diplayed_the_message(Steps.java:101)
at ✽.It shoulld diplayed the message 'Please Enter the valid number format'(file:///C:/Users/DELL/eclipse-workspace/RLL_Project_ContactUs/RLL_project_ContactUsForm/src/test/resource/features/ContactUs.feature:14)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.app.runner.TestNGRunner" name="runScenario" time="32.680">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.app.runner.TestNGRunner" name="runScenario" time="33.139">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- com.app.runner.TestNGRunner -->
